### ISSUE TITLE
[BUG] Incompatibility with 'Slight' GUI Modifications

### ISSUE THREAD

**Issue by YTG1234** [juancarloscp52/BedrockIfy#1]
When I install this mod, a Mixin error that contains "slight-gui-modifications" gets thrown: https://hastebin.com/wiberukoge.apache

**Other Info**
MC: 1.16.2
Mod List: https://hastebin.com/xekotelicu

**Comment by YTG1234** [comment]
@juancarloscp52

**Comment by juancarloscp52** [comment]
> When I install this mod, a Mixin error that contains "slight-gui-modifications" gets thrown: https://hastebin.com/wiberukoge.apache
> 
> **Other Info**
> MC: 1.16.2
> Mod List: https://hastebin.com/xekotelicu

BedrockIfy is completely incompatible with slight gui modifications right now as both mods modify the same game components (for features like screen safe area and others). I'll be taking a look into SGM in order to improve compatibility.

**Comment by YTG1234** [comment]
You can maybe implement the GUI animation that sgm does, so I wouldn't need it. The GUI animation is in bedrock edition as well, so nice opportunity there.

[Yonatan Dafna - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=nnhoe)	[nnhoe]

On August 26, 2020 at 11:43 GMT, Juan Carlos <notifications@github.com> wrote:

When I install this mod, a Mixin error that contains "slight-gui-modifications" gets thrown: https://hastebin.com/wiberukoge.apache

Other Info
MC: 1.16.2
Mod List: https://hastebin.com/xekotelicu

BedrockIfy is completely incompatible with slight gui modifications right now as both mods modify the same game components (for features like screen safe area and others). I'll be taking a look into SGM in order to improve compatibility.

**Comment by YTG1234** [comment]
You can maybe implement the GUI animation that sgm does, so I wouldn't need it. The GUI animation is in bedrock edition as well, so nice opportunity there.

**Comment by juancarloscp52** [comment]
I'll take a look at that, as I've already been experimenting with InGameHub animations. But first I'll try to improve compatibility with SGM as it includes some other useful features.

**Comment by juancarloscp52** [comment]
@YTG1234 I've fixed the issue and now 'Slight' GUI modifications is compatible with BedrockIfy since commit 7aeacf9d06edceaee6f4f57261ab3947dc7ad17a. Most features work except the 'custom slot highlighting' as bedrockIfy uses it's own highlighting.

This change is included in BedrockIfy 0.1.2 that can be downloaded from the [release page](https://github.com/juancarloscp52/BedrockIfy/releases).
