### ISSUE TITLE
Animated chest icon at saving

### ISSUE THREAD

**Issue by E404NNF** [juancarloscp52/BedrockIfy#10]
There's usually an option to toggle a animated chest icon on bedrock that appears every time the world is autosaved or when leaving a server or world, hope this gets added to this mod.

**Comment by juancarloscp52** [comment]
Thanks, good idea. I'll have it ready for the next update.

**Comment by E404NNF** [comment]
Aight thanks!

**Comment by juancarloscp52** [comment]
Implemented in commit dd3bcada5843d7099754fe363cf3b059b2a5b992. You can download the lasted version from the [releases](https://github.com/juancarloscp52/BedrockIfy/releases) page.

**Comment by E404NNF** [comment]
Nice
