### ISSUE TITLE
Appleskin saturation overlay working with bedrockify safe zone

### ISSUE THREAD

**Issue by dude98** [juancarloscp52/BedrockIfy#102]
i sent a request to appleskin's github and they sent their "for mod developers" section, i was wondering if you could make it so the mods work together to have a floating hotbar and saturation from the other mod still lining up. it'd be great to have them visible on worlds without issue.

**Comment by juancarloscp52** [comment]
Thanks! I did not know about the AppleSkin API, I'll take a look as soon as posible

**Comment by juancarloscp52** [comment]
Just pushed the commit adding compatibility. It will included with the next version of bedrockIfy when more updates/bug fixes are present. Until then, you can try this changes building the mod from the github source
