### ISSUE TITLE
Touch controls

### ISSUE THREAD

**Issue by Poopooracoocoo** [juancarloscp52/BedrockIfy#105]
Support for touchscreen input was dropped in [Lambda Controls](https://github.com/LambdAurora/LambdaControls) as of v1.7.0

I'd love to see touch controls from this mod! ^.^

**Comment by juancarloscp52** [comment]
Hi! Unfortunately I do not plan on supporting touchscreen input at the moment

**Comment by Poopooracoocoo** [comment]
@juancarloscp52 Mind updating the README?

**Comment by juancarloscp52** [comment]
done!
