### ISSUE TITLE
Crash on boot with Bedrockify (MC 1.17.1, Mod v1.2)

### ISSUE THREAD

**Issue by Mistyttm** [juancarloscp52/BedrockIfy#113]
Minecraft manages to launch to the point of loading the Minecraft window, and then crashing

Here's the crash report:
[crash-2021-10-31_13.49.50-client.txt](https://github.com/juancarloscp52/BedrockIfy/files/7448041/crash-2021-10-31_13.49.50-client.txt)

Is there an incompatibility with Optifine? Because that's the only thing I could think of

**Comment by juancarloscp52** [comment]
Optifine might be sometimes incompatible with bedrockIfy. But lets try fixing it:

Open your minecraft instance with only bedrockIfy (and fabric & fabric api) enabled. Go to bedrockIfy Settings, into the "Mixins" tab and search for "client.features.bedrockShading" and disable this mixin. Save changes and close the game. Now you should be able to enable the rest of the mods and check if it now works.

**Comment by Mistyttm** [comment]
This fixed it, thank you!
Would you like a copy of the log before and after it was fixed so you can see what exactly caused it? I have over 80 mods installed now and any one of them could have caused it

**Comment by juancarloscp52** [comment]
Great! I'm pretty sure it was optifabric
