### ISSUE TITLE
[BUG] Extended Armor Bars or Health Overlay Crash

### ISSUE THREAD

**Issue by BaeyDesola** [juancarloscp52/BedrockIfy#117]
bedrockify-1.2.0 + extended-armor-bars-1.1.0 or/ HealthOverlay-1.17.1-4.0.2  
The same crash happens when you start the game

**Comment by Delfite** [comment]
> bedrockify-1.2.0 + extended-armor-bars-1.1.0 or/ HealthOverlay-1.17.1-4.0.2 The same crash happens when you start the game

Providing the relevant crash log (I'm sure) would help immensely with fixing this issue.

**Comment by juancarloscp52** [comment]
Cannot reproduce crashes with bedrockify on 1.19 versions for both extended armor bars and health overlay
