### ISSUE TITLE
Suggestion: Bedrock's 3D Fishing Hooks

### ISSUE THREAD

**Issue by apicella1** [juancarloscp52/BedrockIfy#119]
Bedrock has a 3D fishing hook/bobber compared to Java's 2D one. This somewhat makes it more useful than the 2D one because it's easier to see if it bobs under the water from further distances. 

 I actually tried adding 3D fishing hooks to Java myself a few months ago with Optifine, but Optifine didn't have the capability of doing so. Even though It didn't work for me, You will probably have better luck with the model and texture in the game. Below, I've submitted the Blockbench file. I've hand-edited it and converted it into a generic model instead of an Optifine entity. It uses the same Textures from bedrock. I don't know if this will be of any use, but you have my permission to use this if needed. 
[fishinghookbedrock.zip](https://github.com/juancarloscp52/BedrockIfy/files/7586272/fishinghookbedrock.zip)

This is what it looks like in Bedrock:
![image](https://user-images.githubusercontent.com/60238996/142983580-b089c61a-c604-4a22-a726-884a5d9add55.png)

This is what It looks like in Java:
![image](https://user-images.githubusercontent.com/60238996/142985726-f83c7832-7d22-4d8a-90b5-43995fb47d6e.png)
[images from the Minecraft Wiki.]

**Comment by lonefelidae16** [comment]
Hi, I didn’t know the Bedrock’s fishing bobber was 3D until I saw this issue. I think it’s a nice feature! And the model data you have is also very helpful for me, thank you so much.

![2023-01-26 20-23-22](https://user-images.githubusercontent.com/74746227/214837394-9922571e-ac85-4d2a-8fff-07e1f878bce9.png)

Implementing this feature renders the rod string in weird position, but I don’t think it’s a good idea to modify this rendering method as there may be some changes in a future update. So I’ll leave it alone.

I will create a new PR soon. It would be wasteful to keep this feature to myself.
