### ISSUE TITLE
Noticeable lighting difference in the nether

### ISSUE THREAD

**Issue by E404NNF** [juancarloscp52/BedrockIfy#12]
In Bedrock edition the nether seems to have a color difference (Fancy graphics in both screenshots)
![Screenshot from 2020-09-27 05-34-30](https://user-images.githubusercontent.com/37207067/94368860-cf941a80-00e6-11eb-8c6a-14505b7762d8.png)
![2020-09-27_05 36 36](https://user-images.githubusercontent.com/37207067/94368872-e0dd2700-00e6-11eb-8a85-0813780effff.png)

**Comment by timelady-victorious** [comment]
Lol the only way i could tell which was Java was the subtitles

**Comment by juancarloscp52** [comment]
This differences exists because Java and bedrock uses different engines. Imitating this small difference would be a big task and I dont consider it necessary yet and it wont bring a big improvement.

**Comment by Saraistupid** [comment]
> This differences exists because Java and bedrock uses different engines. Imitating this small difference would be a big task and I dont consider it necessary yet and it wont bring a big improvement.

Understandable, thanks anyways

**Comment by GamerGever** [comment]
Would be easier to see the differences if you didn't use a different render distance, different texture packs and disabled particles in the Java version...
