### ISSUE TITLE
Suggestion: Bedrock leaves while snowing

### ISSUE THREAD

**Issue by apicella1** [juancarloscp52/BedrockIfy#121]
In Bedrock, the leaves will slowly turn white when it starts snowing. Bedrock has a separate colormap for leaves called foliage.png which I would speculate is used to show the color of leaves in other biomes and also when it snows in-game. Another thing I would like to note is that the leaves don't turn to white instantly, but have a gradual shift to that color from green to white.  Also, the Leaves only turn white when exposed to the snow. So if there were to be a block above it besides another leaf block, it will not be white. 

**Image comparing the Leaves when it's not exposed to when it is exposed with another leaf block under it.**
![image](https://user-images.githubusercontent.com/60238996/142992180-b62934d4-8932-4579-8b3a-190ba021577f.png)

**Comment by juancarloscp52** [comment]
Hi! Thanks for your detailed suggestions.

I've already tried multiple times to implement this feature in java edition. Sadly I think it is not possible currently. I've gotten able to change leaves colors on snowy biomes. But in the current state of the game, I've not been able to update the color of leaves on already rendered chunks when it starts snowing/raining without reloading chunk data (which requires a lot of time).

**Comment by K0-RR** [comment]
@juancarloscp52 You probably know about it but there is a fabric mod called Snowy leaves that implements this. It's open-source so maybe its code could be helpful? Sadly it's not updated anymore - stuck on 1.16.4.
https://github.com/Ashley1227/snowy-leaves
https://www.curseforge.com/minecraft/mc-mods/snowy-leaves

**Comment by juancarloscp52** [comment]
yep, the implementation I did at the time was similar to the one snowy leaves uses. If I remember correctly, the same problem still occurs in the mod. The update of the leaves only occurs randomly while snowing, it does not update the states of all blocks simultaneously as bedrock does.
