### ISSUE TITLE
[v1.18/1.3.0] Mod immediately crashes on Linux within MultiMC 5

### ISSUE THREAD

**Issue by EeveeEuphoria** [juancarloscp52/BedrockIfy#125]
Hey there, I'm not sure why this mod is crashing but... it is? I'm using Fabric 0.12.8, and the only other mod I have enabled is Sodium. In which, it still crashes when I disable Sodium.

Linux distro is rebornOS (based off Arch), I'm on x86_64, and I'm using Nvidia's Drivers (alongside Bumblebee, which forces the nvidia card to work; for the record not using this still causes the crash). MultiMC 5 is on version 0.6.13-2519, latest version on the AUR at the time of writing.

I've provided the full log that MultiMC5 produces in the console

EDIT: I've also tested with Fabric version 0.12.6 and 0.12.7, still crashes with about the same results

[crashlog.txt](https://github.com/juancarloscp52/BedrockIfy/files/7636704/crashlog.txt)

**Comment by EeveeEuphoria** [comment]
Ah, my bad, for some reason I'm not given the usual issue of "this mod is required" for the Fabric API, which mysteriously went missing? It works when installing that now, my apologies lol

**Comment by juancarloscp52** [comment]
Nice! I'll check if the missing "this mod is required" message is from my end ;)
