### ISSUE TITLE
Incompatible With Replay Mod

### ISSUE THREAD

**Issue by ColRealPro** [juancarloscp52/BedrockIfy#128]
when you go to render a video in replay mod with bedrockify installed, Rendering will fail and your game's UI will become invisible, Controls will also be completely disabled

**Comment by juancarloscp52** [comment]
Crashes with:
 `Mixin apply for mod (unknown) failed mixins.compat.shaders.replaymod.json:MixinShaderRenderChunk -> net.minecraft.class_846$class_851: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field rebuildFrame was not located in the target class net.minecraft.class_846$class_851. Using refmap mixins.replaymod.refmap.json` 
BedrockIfy should not really modify any of the related mixins (chunkbuilder or ChunkBuilder). So I do not really understand why is failing with bedrociIfy
