### ISSUE TITLE
Incompatible with FancyMenu

### ISSUE THREAD

**Issue by yum13241** [juancarloscp52/BedrockIfy#130]
With old panorama on, they layout just breaks entirely, and lately with my FancyMenu layout the Minecraft logo disappears.

**Comment by juancarloscp52** [comment]
Hi! Please include screenshots of the problem, and the layout you are using. I'm unable to reproduce this bug

**Comment by yum13241** [comment]
I'm the stupid one, turns out I hid the logo on accident.
