### ISSUE TITLE
Incompatible with Panorama Tweaker

### ISSUE THREAD

**Issue by Slooshie1** [juancarloscp52/BedrockIfy#133]
Panorama Tweaker allows you to change the speed, angle, etc. of the background panorama, but this mod completely disables that feature. I have set the panorama to rotate as fast as possible and I have changed the camera angle so that it always faces straight ahead (like in Bedrock Edition), but when I go back to the main menu, the panorama is still moving slowly (vanilla speed) and the camera angle is still pointed downward.
![image](https://user-images.githubusercontent.com/90230538/150697864-437e591f-bbfe-4b3b-b128-547d523026ba.png)
This is a conversation I had with the creator of Panorama Tweaker in an issue thread on their github page.

**Comment by juancarloscp52** [comment]
Thanks for reporting this issue! I'll see what I can do as soon as posible

**Comment by TurtleArmyMc** [comment]
Panorama Tweaker works fine with Bedrockify now.

**Comment by Slooshie1** [comment]
the panorama is a bit stuttery. I only notices it when I make the panorama rotate fast, so I'm not sure if it's still a slight incompatibility issue or if Bedrockify causes stuttering by default. The panorama is smooth when I disable bedrockify

**Comment by Slooshie1** [comment]
https://user-images.githubusercontent.com/90230538/151711916-c0893090-c493-4999-b1a4-efc39f1a4924.mp4

here is an example of Bedrockify making the panorama laggy

**Comment by Slooshie1** [comment]
weird, it seemed to randomly go away after a few hours (and no, it wasn't after a simple MC restart, I actually relaunched Minecraft multiple times today).
