### ISSUE TITLE
[Bug] Incorrect text size

### ISSUE THREAD

**Issue by RyanCR03** [juancarloscp52/BedrockIfy#138]
the text size in the loading screen does not seem to scale correctly with the configured gui scale. (gui scale in example: 3)
![image](https://user-images.githubusercontent.com/32957560/153509049-192a0bac-0887-4bae-93f4-b1c28c8e7567.png)

**Comment by juancarloscp52** [comment]
Hi! I can't seem to find the root of the issue. I'm rendering the text in the same way as the other texts in the game. Might be a Minecraft Issue

**Comment by RyanCR03** [comment]
the issue only seems to occur when the gui scale is set to any number other than 2. the way I've noticed how the gui scale works is that whatever number it is, is the height and width of every gui pixel (in this example it is 3). the text may be trying to be the wrong size.

**Comment by RyanCR03** [comment]
i dont know any java but i checked the code and it might have something to do with 
```
        int xPosition = this.width / 2;
        int yPosition = this.height / 2;
```
in `src/main/java/me/juancarloscp52/bedrockify/mixin/client/features/loadingScreens/LevelLoadingScreenMixin.java`
on line 40 and 41

i noticed the text only looked normal on gui size 2 and these values are 2, so ¯\_(ツ)_/¯.

**Comment by juancarloscp52** [comment]
You were right! The issue was that the x and y position at that scale was a floating point number instead of an integer, and minecraft scaling was getting confused. Thanks for posting this issue
