### ISSUE TITLE
Reactivate Elytra after cancelling it midfly requieres double tap on spacebar

### ISSUE THREAD

**Issue by igoticecream** [juancarloscp52/BedrockIfy#140]
Hello, just a minor difference between BE and your implementation.

On BE, after closing the elytra and you start falling, you can redeploy it by a single tap on spacebar. On your mod, requieres to double tap it.

**Comment by juancarloscp52** [comment]
Yeah, I've noticed this difference while developing the feature. But I've not been able to locate the issue yet.

**Comment by igoticecream** [comment]
I found a fix, i'll send you a pull request
