### ISSUE TITLE
How to Disable Grass Color Noise

### ISSUE THREAD

**Issue by StartsMercury** [juancarloscp52/BedrockIfy#142]
Excuse my inability to find it.

`bedrockify-1.4.0+mc1.18.1`

**Comment by StartsMercury** [comment]
~~**Warning:** This solution is not tested, and if it was tested then this notice would be removed accordingly.~~

# Solution

 1. Locate you minecraft folder
 2. Open `config/bedrockifyMixins.json`
 3. Change `"client.features.worldColorNoise":true` to `"client.features.worldColorNoise":false`
    - You can use your file editor's Find/Replace feature if it exist.

**Comment by juancarloscp52** [comment]
Hi! that is a correct solution, another way is to open the bedrockIfy settings menu, go to the Mixins tab and search for the `client.features.worldColorNoise` and disable it
