### ISSUE TITLE
Not working on 1.18.2

### ISSUE THREAD

**Issue by Ultmate-Mario** [juancarloscp52/BedrockIfy#145]
I have the newest version 1.4.1 and when I try to launch minecraft it just crashes. 

The launcher error says "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bedrockify'!
Exit Code: -1"

Here's the crash log:
[crash-2022-04-05_09.10.05-client.txt](https://github.com/juancarloscp52/BedrockIfy/files/8420010/crash-2022-04-05_09.10.05-client.txt)
 
Hopefully this helps fix this.

**Comment by juancarloscp52** [comment]
Seems that it is caused by an incompatibility with another mod modifying world generation. In the mean time, you can change in `.minecraft/config/bedrockifyMixin.json` the entry `common.features.worldGeneration` to false.

**Comment by Ultmate-Mario** [comment]
It was set to false. I set it to true and it fixed it.
