### ISSUE TITLE
Odd shading on paper doll

### ISSUE THREAD

**Issue by poly2it** [juancarloscp52/BedrockIfy#147]
The shading on the paper doll seems to be broken, sometimes parts become really dark. A suggestion to fix this would be to use the same rendering for the paper doll as the one used in the vanilla inventory.

**Comment by juancarloscp52** [comment]
Hi! this is a known, issue. In fact, the doll overlay uses the same rendering as in the inventory. I haven't been able to find the cause of this difference yet.

**Comment by lonefelidae16** [comment]
Hi, I’ve checked and found that the shaders are set up for 3D rendering on InventoryScreen. So I made a small change to support flat shading and it seems to work. Here is a test movie.

https://user-images.githubusercontent.com/74746227/213920035-e7a47886-d758-43c0-822c-f61809e5f8ce.mp4

I will create a new PR for this fix after some testing.
