### ISSUE TITLE
Position and FPS labels overlap

### ISSUE THREAD

**Issue by poly2it** [juancarloscp52/BedrockIfy#148]
The Position label and FPS label overlap by two pixels.

**Comment by juancarloscp52** [comment]
Please send a screenshot showing the issue. Thanks

**Comment by poly2it** [comment]
![Screenshot from 2023-04-02 15-43-13](https://user-images.githubusercontent.com/84731064/229356727-0e9c155a-6824-4953-9ba0-8d236f4e3a93.png)
bedrockify-1.5.1+mc1.19.1

**Comment by poly2it** [comment]
@juancarloscp52 
This can be reopened now.
