### ISSUE TITLE
crash/incompat with debugify

### ISSUE THREAD

**Issue by DioEgizio** [juancarloscp52/BedrockIfy#149]
https://github.com/W-OVERFLOW/Debugify/issues/76#issuecomment-1103983642

https://0x0.st/oTih.txt

**Comment by juancarloscp52** [comment]
should be fixed now (adbfdac41ed42ec9fe24f7f63432a7dee65abb9f)

**Comment by DioEgizio** [comment]
Yeah seems to work now. Thanks
