### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by FortiethSwing61** [juancarloscp52/BedrockIfy#153]
1.18.2 version doesn't load

**Comment by ghost** [comment]
1.19

**Comment by FortiethSwing61** [comment]
I mean Bedrockify's version for 1.18.2 doesn't work

**Comment by juancarloscp52** [comment]
Hi! Im working on porting it to 1.19, hopefully have it for tomorrow!

**Comment by juancarloscp52** [comment]
[1.19 version](https://www.curseforge.com/minecraft/mc-mods/bedrockify) have been released! enjoy it!
