### ISSUE TITLE
[Log] Crash when disabling word generation mixin (I don't use the dead/fall tree thing)

### ISSUE THREAD

**Issue by ardissaps** [juancarloscp52/BedrockIfy#155]
Crashlog : 
https://pastebin.com/y68ypdet

Launcher Log :
https://paste.atlauncher.com/view/667b6b96-9aac-461d-b703-fedafdf2233a

Only need the interface thing feature.

**Comment by juancarloscp52** [comment]
Hi! don't disable that mixin, just use the option in the General tab of bedrockIfy settings. I'll hide that mixin from the menu for the next version to avoid these problems.
