### ISSUE TITLE
Selected hotbar slot texture is broken

### ISSUE THREAD

**Issue by Khodyn** [juancarloscp52/BedrockIfy#157]
With BedrockIfy:
![image](https://user-images.githubusercontent.com/49518050/173797368-40d9110a-27e1-4e6a-b011-bf0e6a4e1f59.png)
Vanilla:
![image](https://user-images.githubusercontent.com/49518050/173797906-dea44d6f-5102-41b1-9100-adb74850e713.png)

**Comment by juancarloscp52** [comment]
Im not able to replicate this issue with bedrockify...
BedrockIfy:
![image](https://user-images.githubusercontent.com/11300094/195141614-a71bb86f-6b71-4bf7-9d12-4ae73be03dad.png)
Minecraft Bedrock Edition:
![image](https://user-images.githubusercontent.com/11300094/195140683-82004ba7-0711-4464-ae22-0f7fb367cca8.png)

**Comment by antieksi** [comment]
kinda late, but looks like this issue occurs only with resourcepacks that replace assets/minecraft/textures/gui/widgets.png texture. for the context: i have vanillatweaks dark gui, and this is how this bug looks for me
![изображение](https://user-images.githubusercontent.com/95758843/218475700-de8e14f4-63fd-4cc2-a2a8-cb9a2d7df861.png)

**Comment by juancarloscp52** [comment]
Thanks for the info. Will take a look!

**Comment by juancarloscp52** [comment]
I've been looking into it, but I cannot reproduce with vanilla tweaks in mc 1.19.3 and 1.19.4, hotbar seems fine.
![image](https://user-images.githubusercontent.com/11300094/229366904-64031591-a582-4d17-9b48-91cc4abd771c.png)
