### ISSUE TITLE
Panorama Background On All Screens breaks Language Reload mod

### ISSUE THREAD

**Issue by baobuh** [juancarloscp52/BedrockIfy#163]
Toggling this option prevents you from selecting languages on the new Language Reload's UI and partially breaks it

**Comment by juancarloscp52** [comment]
Hi! Fixed with commit https://github.com/juancarloscp52/BedrockIfy/commit/7cb97f870e60ff5977e0b4c7665073bd9cb17a29, it wil be available with the next bedrockIfy release
