### ISSUE TITLE
[Suggestion] HUD Opacity from Bedrock Video Settings

### ISSUE THREAD

**Issue by lunarbunten** [juancarloscp52/BedrockIfy#164]
In Bedrock, there is an option called "HUD Opacity" that controls the resting opacity of the HUD. After a few seconds of inactivity, the HUD will begin to fade to the set opacity level (a range of 1-100%). The HUD will return to it's normal opacity when the player changes hotbar slots.

This is likely difficult to implement, but I feel it would be an interesting addition

**Comment by juancarloscp52** [comment]
Hello! sorry for the late response. these days I've been preparing a prototype for this feature and I've found out that it is impossible to make the items in the hotbar transparent.

https://user-images.githubusercontent.com/11300094/212750077-e1e0a660-5bb5-4a6f-841c-e2f96b652c42.mp4

I'm posting it here in case someone happens to read this and has a solution. Anyways I think that I still will continue with this implementation as the rest of the gui seems that can be correctly made transparent.

**Comment by juancarloscp52** [comment]
Forgot to update you... This feature was added in bedrockIfy 1.6!
