### ISSUE TITLE
Breakes Xaero's minimap Potion effects push box

### ISSUE THREAD

**Issue by SuusHex008000** [juancarloscp52/BedrockIfy#165]
With Xaero's minimap you can set up a push box for the potion effect so the effect icons are not overlapping with the map. With bedrocklfy enabled this function is not working anymore. Also status effect timer won't work.

**Comment by juancarloscp52** [comment]
Hi! Unfortunately there is no way to prevent status effects from overlapping the map when a high value of "screen safe area" is used. The only way is to set the screen safe area to 0 in bedrockIfy settings. 
About status effect timer, with the next bedrockify update timers will work as expected when screen safe area is 0. Sadly, that mod is not codded in a compatible way to make it work with screen safe area>0. If you still want to use screen safe area, please use Status Effects Bars mod.
Thanks for opening the issue!
