### ISSUE TITLE
In-game Iris menu loads with dirt background.

### ISSUE THREAD

**Issue by Slooshie1** [juancarloscp52/BedrockIfy#172]
When using Bedrockify with Iris on 1.19.2, the in-game iris shaders menu renders with the dirt background instead of showing the game in the background.

**Comment by Slooshie1** [comment]
This did not happen on 1.19 btw

**Comment by lonefelidae16** [comment]
Sorry, that’s due to PR #162 and my carelessness. I’m writing a patch.
