### ISSUE TITLE
package a release for commit 9fb08cd for users stuck on 1.19

### ISSUE THREAD

**Issue by Godeps2891** [juancarloscp52/BedrockIfy#174]
the latest bedrockify version only supports 1.19.1+, pull #162 was compatible with 1.19 though, so i'm asking if it could be packaged as a jar and released on modrinth & curseforge for easy integration into modpacks

**Comment by juancarloscp52** [comment]
I've just uploaded it to [modrinth](https://modrinth.com/mod/bedrockify/version/1.4.2b%2Bmc1.19) and soon will be available in [curseforge](https://www.curseforge.com/minecraft/mc-mods/bedrockify/files/3948832) when it finishes processing! Thanks for reporting the issue
