### ISSUE TITLE
[Crash] Mixin incompatability

### ISSUE THREAD

**Issue by Dakedres** [juancarloscp52/BedrockIfy#178]
Minecraft version: 1.19.2
Bedrockify version: 1.4.2b
Quilt version: 0.17.4
QSL version: 4.0.0-beta.9+0.60.0

[Crash log](https://paste.ee/p/4vtkt)

**Comment by juancarloscp52** [comment]
Hi! BedrockIfy 1.4.2b is only compatible with minecraft 1.19 (as labeled on the download title). For 1.19.2 use [BedrockIfy 1.4.2 ](https://www.curseforge.com/minecraft/mc-mods/bedrockify/files/3906222)(the one without the letter).
