### ISSUE TITLE
Incompatible with Xanders Sodium Options.

### ISSUE THREAD

**Issue by ghost** [juancarloscp52/BedrockIfy#184]
> # With [BedrockIfy](https://modrinth.com/mod/bedrockify)
> #
![image](https://user-images.githubusercontent.com/65317484/194953501-922faa5f-f27f-46e2-b41e-e736a20eecc3.png)

> ## Without [BedrockIfy](https://modrinth.com/mod/bedrockify)
> #
> ### _Image taken from Xander's Sodium Options gallery page on modrinth_
![image](https://user-images.githubusercontent.com/65317484/194953682-62d92361-3fd8-4750-ae0e-92b57f495e8a.png)

**Comment by juancarloscp52** [comment]
Hi! Fixed with commit 7cb97f870e60ff5977e0b4c7665073bd9cb17a29, it wil be available with the next bedrockIfy release
