### ISSUE TITLE
[suggestion] fortune can be used on flowers and crops

### ISSUE THREAD

**Issue by DaPhysikist** [juancarloscp52/BedrockIfy#187]
On bedrock edition, a tool with fortune can be used to harvest crops and flowers, which yields more than what a player would receive breaking them without fortune. This would be a cool feature to see on Java.

**Comment by juancarloscp52** [comment]
Fortune already affects crops. In BE, fortune only affects tall flowers when broken from the lower block. This is considered a bug that can be tracked [here](https://bugs.mojang.com/browse/MCPE-18880) and was reopened by mojang staff this year (after being closed for 6 years) so it will probably be fixed soon. For now I will not include this feature in bedrockIfy
