### ISSUE TITLE
Button overlap with essential

### ISSUE THREAD

**Issue by ManInMyVan** [juancarloscp52/BedrockIfy#192]
[mod page](essential.gg)
The fix didn't fix it

**Comment by juancarloscp52** [comment]
Hmm I see, What version of Minecraft, BedrockIfy and essentials are you using. Can you please send a minecraft log with bedrockIfy and essentials running? Thanks.

**Comment by ManInMyVan** [comment]
Minecraft: 1.19.2
Bedrockify: 1.5.1 (I think. It's the latest one, I updated it just before creating this  issue)
Essential: idk, I'll tell you when I know
Logs: I'll give you a patebin link when I get the logs

**Comment by ManInMyVan** [comment]
Essential: 1.0.0
Will latest.log work?

**Comment by juancarloscp52** [comment]
Yes!

**Comment by ManInMyVan** [comment]
Pastebin won't let me create the paste because it says it contains potentially offensive stuff.

**Comment by ManInMyVan** [comment]
[controlc.com/08cff24f](controlc.com/08cff24f) (link to latest.log)

**Comment by juancarloscp52** [comment]
[bedrockify-1.5.2-SNAPSHOT+mc1.19.1.zip](https://github.com/juancarloscp52/BedrockIfy/files/9895641/bedrockify-1.5.2-SNAPSHOT%2Bmc1.19.1.zip)

Try this version of the mod (you have to unzip it) and let me know if it fixes it.

**Comment by ManInMyVan** [comment]
It's fixed

**Comment by juancarloscp52** [comment]
Perfect! Thanks for opening the issue! This fix will be included with the next version
