### ISSUE TITLE
Cannot invoke "net.minecraft.class_4184.method_19326()" because "this.field_4686" is null

### ISSUE THREAD

**Issue by ghost** [juancarloscp52/BedrockIfy#193]
> java.lang.NullPointerException: **Cannot invoke "net.minecraft.class_4184.method_19326()" because "this.field_4686" is null**
> 	at net.minecraft.class_898.method_23168(class_898.java:363)
> 	at net.minecraft.class_922.method_4055(class_922.java:246)
> 	at net.minecraft.class_922.method_3921(class_922.java:29)
> 	at net.minecraft.class_897.method_3936(class_897.java:68)
> 	at net.minecraft.class_922.method_4054(class_922.java:150)
> 	at net.minecraft.class_1007.method_4215(class_1007.java:63)
> 	at net.minecraft.class_1007.method_3936(class_1007.java:41)
> 	at net.minecraft.class_898.method_3954(class_898.java:141)
> 	at me.juancarloscp52.bedrockify.client.features.paperDoll.PaperDoll.lambda$drawPaperDoll$1(PaperDoll.java:108)
> 	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171)
> 	at me.juancarloscp52.bedrockify.client.features.paperDoll.PaperDoll.drawPaperDoll(PaperDoll.java:108)
> 	at me.juancarloscp52.bedrockify.client.features.paperDoll.PaperDoll.renderPaperDoll(PaperDoll.java:57)
> 	at me.juancarloscp52.bedrockify.client.gui.Overlay.renderOverlay(Overlay.java:36)
> 	at me.juancarloscp52.bedrockify.client.BedrockifyClient.lambda$onInitializeClient$3(BedrockifyClient.java:88)
> 	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
> 	at net.minecraft.class_329.handler$chn002$render(class_329.java:4997)
> 	at net.minecraft.class_329.method_1753(class_329.java:393)
> 	at net.minecraft.class_757.method_3192(class_757.java:862)
> 	at net.minecraft.class_310.method_1523(class_310.java:1177)
> 	at net.minecraft.class_310.method_1514(class_310.java:768)
> 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
> 	at net.minecraft.client.main.Main.main(Main.java:51)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:471)
> 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
> 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
> 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
> 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
> ### [Crash-Report](https://github.com/juancarloscp52/BedrockIfy/files/10071388/crash-2022-11-22_12.08.50-client.txt)
> ### [Latest-log](https://github.com/juancarloscp52/BedrockIfy/files/10071408/latest.log)

**Comment by juancarloscp52** [comment]
Hey! Sorry for the late response.

This issue is happening at unmodified minecraft code (although bedrockIfy does call to it for rendering the paper doll) and happens that the camera does not exists yet. I suspect this might be caused by another mod that is modifying something related to camera, or rendering of entities (or player entity).

do you have a mod pack link so I can test in the same environment? Thanks!

**Comment by ghost** [comment]
I can not access my computer right now since I'm on vacation. Also, because of the 1.19.3 update, I probably will not be able to find which mod caused the issue.
Very sorry

**Comment by juancarloscp52** [comment]
No problem at all, happy holidays.

**Comment by ghost** [comment]
I believe I might have a backup of my 1.19.2 mods but although, I won't be available until tomorrow at around 6 PM.

**Comment by juancarloscp52** [comment]
No problem, whenever you can.

**Comment by ghost** [comment]
Very sorry for the deley. I will take a look at my 1.19.2 mods when I'm able to use my computer.

**Comment by ghost** [comment]
It can not seem to launch minecraft on 1.19.2 with my old mods as of right now so this might take up to a day. My bad.
