### ISSUE TITLE
doesn't launch on 1.19.3

### ISSUE THREAD

**Issue by litoj** [juancarloscp52/BedrockIfy#195]

**Comment by juancarloscp52** [comment]
Hello! I'm working on porting to 1.19.3, there has been big changes in world generation and I hope to have it ported in a day or two.

**Comment by litoj** [comment]
Thank you. btw sorry for the plain issue, I just forgot to include the log, but I suppose you already know where the problems are.
Also, your mod is awesome, the reach around feature is something I sought for for a really long time and find it irreplaceable.

**Comment by juancarloscp52** [comment]
Hi there! Just released a version compatible with 1.19.3. You can find it in GH releases, modrinth and in curseforge (pending review).
