### ISSUE TITLE
[Crash] Tooltip feature causing crash "java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129"

### ISSUE THREAD

**Issue by Timolino456** [juancarloscp52/BedrockIfy#196]
Long story short: At some point, the game started crashing when opening my inventory or the main menu *sometimes*. It always showed random mods in the stacktrace which had their own GUIs. Then it started crashing when hovering my mouse above certain items. I'm not 100% sure if these two were also caused by Bedrockify, but the following definitely was. When I switch items in my hotbar to certain ones, the game freezes and crashes. In both cases, the items had a couple enchantments. The error mentioned in the title was always the same. The stacktrace also always mentions fastutil (not sure if that's relevant).

Crash log: https://mclo.gs/971BcUX

I really hope this is the actual root of the issue, I'm so tired of this error lol.
It was a pain figuring this one out because it never showed Bedrockify in the stack trace until the hotbar switching crash.
Disabling the tooltip feature fixed this and the crashes when hovering mouse above the items that consistently made the crash happen, so I'm guessing it is caused by Bedrockify.

**Comment by juancarloscp52** [comment]
'Hmm Thats a weird bug.... Can you show me the items that makes it crash (name, tooltips, enchantments, etc)

**Comment by Timolino456** [comment]
It turned out that this is a problem of Roughly Enough Items and not Bedrockify. Switching to EMI fixed this annoying issue for me. Would've been a lot easier if it actually said so in the stacktrace. :p
