### ISSUE TITLE
Disabling tree related settings causes issues on worlds

### ISSUE THREAD

**Issue by mineland-0066** [juancarloscp52/BedrockIfy#201]
Disabling fallen trees and dying trees causes an error when trying to load worlds and crashes when loading the world creation screen.

[2022-12-22-7.log](https://github.com/juancarloscp52/BedrockIfy/files/10291261/2022-12-22-7.log)

enabling the settings and relaunching the game fixes the crash.

**Comment by lonefelidae16** [comment]
Can confirm, it’s due to the new Registries system from 1.19.3.

I have written a patch, and confirmed to apply these features without relaunching instance. Also can disable.
I’ll create a PR soon.
