### ISSUE TITLE
Visual conflict with Raised mod

### ISSUE THREAD

**Issue by vrad-exe** [juancarloscp52/BedrockIfy#214]
When Bedrockify and [Raised](https://modrinth.com/mod/raised) are used together, the area used for the selected hotbar slot texture gets expanded twice, causing it to overflow into the disabled button texture. Raised includes some extra functionality that Bedrockify doesn't like being able to customize the hotbar height, so there is reason to use them together.
![image](https://user-images.githubusercontent.com/19228201/215371426-a4d2dc72-ed85-48ec-acfe-d9cfdeddf63f.png)

**Comment by juancarloscp52** [comment]
Hi! I'll take a look at it, in the meantime, bedrockify has a similar feature called screen safe area, where the hotbar is moved in a similar way.
