### ISSUE TITLE
Colormatic Exp Text color gets overriden with the default when using bedrockify Exp text style

### ISSUE THREAD

**Issue by TheDinoKingK** [juancarloscp52/BedrockIfy#222]
I was working on my texture pack when I found the text color doesn't change when you enable this setting and reverts back to the default hardcoded value, if you can fix this that would be great

example:
![Capture](https://user-images.githubusercontent.com/45495320/217107312-ec71ad81-cc45-4237-9e34-f2190bee950f.png)

**Comment by juancarloscp52** [comment]
Hello! For now you can try disabling the mixin `client.features.screenSafeArea` in the mixin tab on bedrockify settings menu. With that said, you will loose the screen safe area feature.

I'll try to get it fixed with the next release.

**Comment by TheDinoKingK** [comment]
alright, thank you

**Comment by juancarloscp52** [comment]
Fixed in c393cff, will be added with the next bedrockify version. Thanks for opening this issue
