### ISSUE TITLE
Mangrove Boat Recipe Does Not Require Shovel

### ISSUE THREAD

**Issue by eithli** [juancarloscp52/BedrockIfy#223]
![image](https://user-images.githubusercontent.com/109933737/217825991-110cd95f-7c55-499e-87c0-f0f5988dfee1.png)

When Bedrock recipes are enabled, it appears that the mangrove boat is exempt from the requirement to include a shovel.

**Comment by juancarloscp52** [comment]
Good catch! Fixed in a983f1c, will be included in the next version.
