### ISSUE TITLE
Can't disable "worldGeneration" mixin

### ISSUE THREAD

**Issue by Rad586** [juancarloscp52/BedrockIfy#225]
Game version: 1.18.2 fabric
Mod version: 1.4.1
Environment:
1. fabric-api-0.67.1+1.18.2
2. bedrockify-1.4.1+mc1.18.2

Description:
Game crashes after disabling "worldGeneration" mixin.

Log:
[latest.log.txt](https://github.com/juancarloscp52/BedrockIfy/files/10740066/latest.log.txt)
Crash report:
[crash-2023-02-15_14.42.59-client.txt](https://github.com/juancarloscp52/BedrockIfy/files/10740071/crash-2023-02-15_14.42.59-client.txt)

**Comment by juancarloscp52** [comment]
Hello!, this was fixed in newer versions of bedrockify. For that version, world generation mixin should not be disabled. Instead if you want to disable its features, disable in settings the "dying trees option). Sorry for the inconvenience.
