### ISSUE TITLE
Update notification appears even though the mod has already been updated

### ISSUE THREAD

**Issue by BetaKors** [juancarloscp52/BedrockIfy#226]
I'm on version 1.6.1 of the mod and a notification — those little diamond thingies — appears on ModMenu telling me to update to version 1.6.0.

![image](https://user-images.githubusercontent.com/88991219/219868423-4bddb710-3f8e-4e6c-87fe-b4e5cc2e57c6.png)

**Comment by BetaKors** [comment]
This bug might actually be on ModMenu's side. Should I open an issue there?

**Comment by lonefelidae16** [comment]
It’s because version 1.6.1 of BedrockIfy has been released as 1.6 and `gradle.properties` has not been changed.

https://github.com/juancarloscp52/BedrockIfy/blob/c393cffe3991fca833ca986a908e78bb422d240b/gradle.properties#L8-L9

It’s 1.6.1 as shown, but internally it’s detected as 1.6, so I guess ModMenu is confused. You can find it in your log.

Maybe it will be fixed in the next version.

**Comment by juancarloscp52** [comment]
Although I did forget to commit the usual "Version Bump" to github with the version changed. That build (both on modrinth and curseforge) had the mod_version in gradle.properties changed. This can be verified by extracting the .jar downloaded from modrinth and checking the fabric.mod.json. I'm unsure of what is causing this.

Also, I'm not able to replicate with bedrockify 1.6.1 and mod menu 5.1.0-beta.4, update notification is not appearing
I'll check in more depth in the following days.

**Comment by juancarloscp52** [comment]
@BetaKors are you using Quilt? I've just noticed that I forgot to set that version as quilt compatible on modrinth and thats why it might be telling you to move to another compatible version. (might be similar to https://github.com/modrinth/code/issues/2660 and https://github.com/TerraformersMC/ModMenu/issues/550)

I've changed the loader compat in modrinth, let me know if the notification still appear

**Comment by BetaKors** [comment]
Yes, I was using Quilt and yes the notification is gone now.

Also, sorry for taking so long to respond!
