### ISSUE TITLE
With Mod Menu Installed you Cant See Desc.

### ISSUE THREAD

**Issue by ZaneDragonBorn** [juancarloscp52/BedrockIfy#23]
Title^
When Viewing A Mod in the Mod Menu it'll Make the text almost impossible to read. View the Picture below for a better understanding...
![image](https://user-images.githubusercontent.com/68198648/96324789-86eac580-0ff1-11eb-8246-e52773ed8fbc.png)
Please either give us the option in mod settings to change the opacity and/or disable it altogether. Or just put a box there (Also I don't like how the top dirt isn't going all the way.

**Comment by juancarloscp52** [comment]
Hi! This is a known issue caused by the option "Panorama background on all screens" when using Mod Menu. You can disable it on BedrockIfy Settings.

**Comment by ZaneDragonBorn** [comment]
> Hi! This is a known issue caused by the option "Panorama background on all screens" when using Mod Menu. You can disable it on BedrockIfy Settings. 

Do you think in future updates you can add an option to turn off the panorama on specific screens? Because I love that feature.

**Comment by juancarloscp52** [comment]
> Do you think in future updates you can add an option to turn off the panorama on specific screens? Because I love that feature.

Just pushed a commit to automatically disable panorama background on the Mod Menu screen. You can try it by building BedrockIfy from source or waiting until the next release.
