### ISSUE TITLE
[Suggestion] Looking at Bedrock Sun.

### ISSUE THREAD

**Issue by eithli** [juancarloscp52/BedrockIfy#233]
When looking at the sun in the Bedrock Edition of the game, the sky becomes a slight shade darker. It would be nice if this feature was implemented in this mod as well.

Picture for reference:
![image](https://user-images.githubusercontent.com/109933737/225739298-7a522cf8-e7df-48a9-ba4c-67a3e30c7406.png)
![image](https://user-images.githubusercontent.com/109933737/225739315-f77edcde-877f-4116-b723-4056d103bde2.png)

**Comment by juancarloscp52** [comment]
Hello! Thanks for the suggestion. This feature has actually already developed for bedrockIfy by @lonefelidae16  and will release in bedrockIfy 1.7 for minecraft 1.19.4 (probably will be released tomorrow)
