### ISSUE TITLE
[Bug] Wrong Exp Level Color

### ISSUE THREAD

**Issue by eithli** [juancarloscp52/BedrockIfy#238]
With the 1.19.4 port of this mod, I hope you realize how much we all appreciate your continuous porting of this mod. However, there could have been a minor oversight on your part. What I mean is that the experience level color is purplish rather than green.

Picture for reference: 
![image](https://user-images.githubusercontent.com/109933737/226115985-c280f70e-91f5-4c09-a11b-fdbf9c833c60.png)

Again, thank you for continuing to port this mod and adding new features to it; I just noticed this and thought I'd let you know.

**Comment by juancarloscp52** [comment]
seems that it was introduce after the initial port to 1.19.4-pre1, to the release version. Such an oversight! Thank you for opening the issue
