### ISSUE TITLE
[Suggestion] Forge 1.12.2

### ISSUE THREAD

**Issue by vico93** [juancarloscp52/BedrockIfy#239]
_I know this is a far-fetched request, but i think it worths the try._

Er... Could it be backported to 1.12? I'm currently "stuck" in that version because some of my mods doesn't update past 1.13, and i really like that mod - honestly this is one of the best incentives i would have to update, because the vanilla stuff... the few relevant for me are already implemented by Future MC.

**Comment by juancarloscp52** [comment]
hello! sadly it is quite difficult to backport bedrockIfy to 1.12... and forge. It is quite a huge mod, and things works really different in those versions.

**Comment by vico93** [comment]
> hello! sadly it is quite difficult to backport bedrockIfy to 1.12... and forge. It is quite a huge mod, and things works really different in those versions.

I totally understand. 
I'm really looking forward to play again with Bedrockify, but unfortunately due to a single (and crucial) plugin that i can only run with my modpack using an hybrid server i'm forced to stay on 1.12.2. That's why i "risked" to do such question.
