### ISSUE TITLE
Hotbar animation error

### ISSUE THREAD

**Issue by tianazhu** [juancarloscp52/BedrockIfy#244]
Version 1.19.4-bedrockify-1.7.1
When a tool with enchanting unbreaking is used, the usage animation is always played instead of when the durability is consumed.

**Comment by tianazhu** [comment]
There is also in the use of fireworks rocket flight when playing animation too fast

**Comment by tianazhu** [comment]
Screenshot demo
This also affects the creative mode
![2023-03-23_08 39 30](https://user-images.githubusercontent.com/95345341/227070046-c84906bc-66d2-4cb8-ada7-9b7bca92e909.png)

![screenshot_demo](https://user-images.githubusercontent.com/95345341/227070692-0c3bd9b7-bfcc-47af-b57f-96a771e89528.png)

**Comment by lonefelidae16** [comment]
Hi! Thank you for your reporting. This is due to #207 , and its spec.

I cannot confirm the original Bedrock spec, but is this the ”wrong” implementation?

If you think so, the animation can also be limited to only when durability is reduced.

**Comment by tianazhu** [comment]
> Hi! Thank you for your reporting. This is due to #207 , and its spec.
> 
> I cannot confirm the original Bedrock spec, but is this the ”wrong” implementation?
> 
> If you think so, the animation can also be limited to only when durability is reduced.

Previous older versions did not have this problem
But after installing bedrockify-1.7.1 there is a problem.

**Comment by lonefelidae16** [comment]
It seems that a spec I implemented as a good idea has turned out to be a problem. Sorry about that.

I will create a new PR so that we can revert to the old version of the spec.
