### ISSUE TITLE
Conflict with Smooth Scrolling Everywhere

### ISSUE THREAD

**Issue by Madis0** [juancarloscp52/BedrockIfy#25]
When "Panorama Background On All Screens" is enabled in BedrockIfy, and the user also has [Smooth Scrolling Everywhere](https://www.curseforge.com/minecraft/mc-mods/smooth-scrolling-everywhere-fabric), it is not possible to use the mouse wheel to scroll in Mod Menu, server list and possibly elsewhere.

BedrockIfy 0.1.7, Smooth Scrolling Everywhere 3.0.3, Fabric API 0.22.1 b 409, Minecraft 1.16.3

**Comment by juancarloscp52** [comment]
This issue should now be completely fixed! Thanks for opening the Issue. You can test this fix by building bedrockIfy from source or wait until the next bedrockIfy release!
