### ISSUE TITLE
[Bug] Chat Opacity Bug

### ISSUE THREAD

**Issue by eithli** [juancarloscp52/BedrockIfy#250]
The chat opacity looks like it's linked to the selected item overlay, as turning the chat opacity to 0 removes the dark background on the tooltips.

With opacity set to 50%:
![image](https://user-images.githubusercontent.com/109933737/227823589-40f4d2a6-9b38-4f90-974b-91825af4f71d.png)![image](https://user-images.githubusercontent.com/109933737/227823553-e87db622-ebbd-4b9c-bf1e-a40b6d1298f7.png)

With opacity set to 0%:
![image](https://user-images.githubusercontent.com/109933737/227823687-c04c12af-39ff-46e8-bbe3-794950717dc3.png)
![image](https://user-images.githubusercontent.com/109933737/227823658-5280274b-2aa3-4087-afe0-7f798f59f1d4.png)

**Comment by juancarloscp52** [comment]
A new option "Tooltips background opacity" has been added to change the tooltip opacity
