### ISSUE TITLE
[Bug]Arrows can not be used on the cauldron

### ISSUE THREAD

**Issue by tianazhu** [juancarloscp52/BedrockIfy#252]
Arrows cannot be turned into tipped arrows in the cauldron, but can be turned into tipped arrows using the cauldron in the bedrock edition

Reference Minecraft Wiki
https://minecraft.fandom.com/wiki/Arrow
![网页捕获_29-3-2023_172840_minecraft fandom com](https://user-images.githubusercontent.com/95345341/228491393-2bc3d8d8-79e5-40ad-912f-cdf3ad738719.jpeg)

**Comment by lonefelidae16** [comment]
Thank you for your reporting. This is the spec suggested by #176 and implemented in #231 .

What other features does the Bedrock cauldron have?

**Comment by lonefelidae16** [comment]
If the “bug” you have pointed out is successfully fixed, it *breaks* the existing world. I would like to avoid another breaking changes any more.

Please let me know if there are other features of the Bedrock’s cauldron that I’ve missed. Let’s implement them all at this time :smiley_cat:

Any feedback is welcome.

**Comment by tianazhu** [comment]
> If the “bug” you have pointed out is successfully fixed, it _breaks_ the existing world. I would like to avoid another breaking changes any more.
> 
> Please let me know if there are other features of the Bedrock’s cauldron that I’ve missed. Let’s implement them all at this time 😺
> 
> Any feedback is welcome.

There is also the cauldron of water can not be mixed by two different dyes out of other colors

Reference Wiki
https://minecraft.fandom.com/wiki/Cauldron
![网页捕获_1-4-2023_182752_minecraft fandom com](https://user-images.githubusercontent.com/95345341/229280845-af14dccb-c0f8-4056-9d0b-63953f2aabb2.jpeg)

**Comment by lonefelidae16** [comment]
> There is also the cauldron of water can not be mixed by two different dyes out of other colors

Oh, good! Thanks for sharing this, I’ll include of this fix.

I also found the Redstone Comparator issue, I’ll try to work on it. But the spec might be a bit different from Bedrock’s.
