### ISSUE TITLE
[Bug] Brewing Stand Item Highlight Issue

### ISSUE THREAD

**Issue by eithli** [juancarloscp52/BedrockIfy#253]
When the potion slot in the brewing stand is hovered over, the potion icon becomes invisible/covered by the mod's item slot feature.
![2023-03-29_18 34 48](https://user-images.githubusercontent.com/109933737/228683153-57c58168-ee73-4563-bda3-a1c71e8ff4fc.png)
![2023-03-29_18 34 50](https://user-images.githubusercontent.com/109933737/228683158-8db71823-2d10-450d-b9b5-176db04c195f.png)

**Comment by juancarloscp52** [comment]
Hello! sadly there is not much I can do about it, those icons are part of the background of that inventory screen, and the highlight draws in front of it. By default, the colors of the highlight are not transparent, causing it to be hidden. One thing you can try is going to settings and changing the first two digits (transparency) of the highlight colors.

This will allow you to see thorugh the highlight and see the icons, but is really tricky to get the colors right.

Most of the other inventories do render these kind of icons on top of the high light. For example, the creative menu armor inventory.
