### ISSUE TITLE
[Issue] Disable Flying Momentum resets on game restart

### ISSUE THREAD

**Issue by bernards934** [juancarloscp52/BedrockIfy#257]
**Versions**
- Minecraft 1.19.2
- Fabric Loader 0.14.12
- Fabric API 0.73.2
- Bedrockify 1.5.1

**Explanation**

The "Disable Flying Momentum" setting parameter resets to OFF when you start the game.
The setting value is not saved upon restart.

**Technical observations**

The `bedrockifyClient.json` config file DOES contain the right value for the key `disableFlyingMomentum` but it still appears as Disabled in the in-game mod settings :
```
{
    // ...
    "disableFlyingMomentum":true
    // ...
}
```

Here is the full `bedrockifyClient.json` file content :
```
{"loadingScreen":false,"bedrockIfyButton":false,"showPositionHUD":false,"FPSHUD":0,"heldItemTooltip":0,"showPaperDoll":false,"showChunkMap":false,"reacharound":true,"reacharoundSneaking":true,"reacharoundIndicator":true,"reacharoundMultiplayer":true,"positionHUDHeight":50,"screenSafeArea":0,"overlayIgnoresSafeArea":false,"cubeMapBackground":false,"bedrockChat":false,"slotHighlight":true,"highLightColor1":-1,"highLightColor2":-9590208,"idleAnimation":1.0,"reacharoundBlockDistance":0.5,"reacharoundPitchAngle":25,"savingOverlay":false,"eatingAnimations":true,"expTextStyle":false,"quickArmorSwap":true,"transparentHotBar":true,"biggerIcons":true,"sneakingShield":true,"bedrockShading":false,"disableFlyingMomentum":true,"elytraStop":true,"panoramaIgnoredScreens":[".modmenu.gui.ModsScreen",".iris.gui.",".modmanager.gui.","yacl.gui.YACLScreen"]}
```

**Comment by juancarloscp52** [comment]
Than you for the detailed issue description, I'll take a look at it in the following days ;)

**Comment by juancarloscp52** [comment]
Hello! I've been trying to replicate your issue, but I haven't been able to do so. Here is what I've tried:

Start BedrockIfy with defualt settings:
- Disable Flying momentum on Settings menu is set to ON, which is correct.
- Flying momentum is disabled while playing

Change disable flying momentum to Off in settings menu:
- flying momentum is enabled while playing
- After restarting, disable flying momentum appears as off, which is correct.

Changing disable flying momentum back to On:
- Flying momentum is disabled while playing
- After restarting, disable flying momentum appears as On, which is correct.

Maybe i am missing something?

**Comment by bernards934** [comment]
Well, I've just tried the following :
- delete the config/bedrockify folder in order to reset the settings
- once the game is started, the "Disable Flying momentum" is set to OFF (while it should be ON)

Also, the "RESET" button at the side is clickable and actually turns it ON.

Maybe I have a conflict with another mod, I'll try to disable everything I can and I keep you updated.

**Comment by bernards934** [comment]
I found it, the issue appears with the MidnightControls mod.
https://modrinth.com/mod/midnightcontrols

I am using version 1.7.4 of this mod.

**Comment by bernards934** [comment]
Alright, I watched over all the settings of this other mod and there is "Fly drifting" parameter which does exactly the same thing,
but if I set it to the same state than it is in Bedrockify, after reboot it's still disabled.

But anyway, I am not sure that's an issue for you to resolve.
Sorry for issue report and for the time you may have spent looking for it..

**Comment by juancarloscp52** [comment]
ok, I've checked and midnight controls implements compatibility with bedrockIfy. As they implement the same feature, the mod disables bedrockIfys drift on start up, thats why you see the setting resetting after restart. For adjusting the drift, modify it in midnight controls settings. Thank you for opening the issue anyways! :)
