### ISSUE TITLE
Setting screen-safe area doesn’t apply to AppleSkin saturation bar

### ISSUE THREAD

**Issue by egeesin** [juancarloscp52/BedrockIfy#26]
When you set any screen-safe area, the AppleSkin indicator that should be placed on the top of hunger bar doesn't align as seen in the image.

![image](https://user-images.githubusercontent.com/8004972/97233687-67714b00-17f0-11eb-8e1a-2afabd409a2a.png)

**Comment by juancarloscp52** [comment]
Hi! This is a known issue and sadly I don't have the means to apply screen border to other mods. If you want to use Apple Skin (or any other mod that applies in game overlays) you should set the screen border to 0.
Sorry for the inconvenience.
