### ISSUE TITLE
Fastloader Mod V3.2.x+ incompatible with Bedrock-Loading-Animation from BedrockIfy

### ISSUE THREAD

**Issue by Cape-City** [juancarloscp52/BedrockIfy#265]
I'm using the Fabric Loader with MC 1.19.3 and i love loading screens and if you get interessting information, it's absolutly fantastic. That's why i love the Bedrock-Loading-Animation from BedrockIfy and had done the translation for it ;). Loading things quickly is awesome too, so i had the mod Fastload installed. With the V3.2.0 and higher of Fastload he changed the complete way how MC is loading worlds (441). Now the mod is skipping the BedrockIfy loadingscreen and shows it's own "starting session" and then further chunk-load information, instead of just adding them to the existing BedrockIfy loadingscreen. I opened a ticket at Fastload, but he said he can't help with this right now and should advise the issue to you, if maybe you can assist in this?

https://github.com/BumbleSoftware/Fastload/issues/71

Happy easter ;)

**Comment by juancarloscp52** [comment]
yep! I can probably try and adapt this screen with bedrockIfy on my part, I'll be taking a look.

**Comment by juancarloscp52** [comment]
![Screenshot from 2023-04-12 22-58-50](https://user-images.githubusercontent.com/11300094/231585689-51cca2b3-e8f8-440e-a1a2-641ed1ae6a2c.png)
Compatibility has been added now (2dfa4dd), it will be released in the next version

**Comment by Cape-City** [comment]
Is there any chance, this fix gets it into the 1.19.3 version, instead only for 1.19.4?
