### ISSUE TITLE
Chat Heads are not shown, if Bedrock style chat is used

### ISSUE THREAD

**Issue by Cape-City** [juancarloscp52/BedrockIfy#271]
When i switch back to java style, the chat head mod works. I testet it with 1.19.4 on fabric:

BedrockIfy - Bedrock Features on Java!
Im_JC52
bedrockify-1.8+mc1.19.4.jar

Chat Heads
dzwdz
chat_heads-0.10.11-fabric-1.19.4.jar

Cloth Config API (Fabric/Forge)
shedaniel
cloth-config-10.0.96-fabric.jar

Fabric API
modmuss50
fabric-api-0.78.0+1.19.4.jar

**Comment by h14turkiye** [comment]
Can confirm, persists in ver 1.9.
