### ISSUE TITLE
[1.16.4] Social Interactions Screen Bugged when Panorama Background on All Screens is turned on

### ISSUE THREAD

**Issue by adamf30** [juancarloscp52/BedrockIfy#28]
![2020-11-02_19 03 13](https://user-images.githubusercontent.com/26857803/97935589-aa767580-1d3e-11eb-9bed-df244c7a2652.png)
1.16.4 was released today, which means the Mod Works. However, there's a gap to fill. When the Social Interactions screen is shown, there is a Leak on the Right.

**Comment by juancarloscp52** [comment]
Hi! this issue have been fixed in bedrockIfy 0.1.9. You can download it through the curseforge page or the github releases page!
