### ISSUE TITLE
Minor Issue in the Menu 

### ISSUE THREAD

**Issue by Kaiji-Key** [juancarloscp52/BedrockIfy#281]
Basically, the "Bedrockify Settings" button overlaps with the button for the Physics Mod. I'm just wondering if you could add an option to turn off button for Bedrockify? So that you can only access the settings using Mod Menu.

![image](https://github.com/juancarloscp52/BedrockIfy/assets/123205194/7bddfbf0-b9a4-447b-9e1f-4f4ea0cb3164)

**Comment by juancarloscp52** [comment]
Hello, you can change the position or hide the settings button already. Go to bedrockify settings, GUI, and look for an option "Bedrockify settings button postion"
