### ISSUE TITLE
Transparent hotbar set to false doesn't work 

### ISSUE THREAD

**Issue by JamesisFonny** [juancarloscp52/BedrockIfy#290]
Setting hotbar transparent to false still make my hotbar transparent
![image](https://github.com/juancarloscp52/BedrockIfy/assets/121544485/b335d7fc-022a-4bc7-9cd0-fc9bb89a093c)

**Comment by lonefelidae16** [comment]
Transparency of Hotbar is based on HudOpacity config value. Currently it’s not enough to set hotbar transparent to false if you want to make Hotbar opaque. But a change is here to prioritize Hotbar and I’m ready to create a pull. https://github.com/lonefelidae16/BedrockIfy/commit/bfd523d2422c302f3caaca1d6afcbe38484d0e43

Juan said “try changing also the hud opacity option”, so I’m not sure I should create a pull.

**Comment by lonefelidae16** [comment]
we can change the name of this settings to avoid misunderstanding:
![Screenshot from 2023-07-23 09-55-54](https://github.com/juancarloscp52/BedrockIfy/assets/74746227/6a19bd97-2e86-4a0d-bc7d-54c6e2aa9c98)

**Comment by juancarloscp52** [comment]
@lonefelidae16 I think that the better option is to implement your suggestion of changing the name of the setting from transparent hotbar to hotbar style (vanilla/bedrock). I'll add this change and update some of the translations. thank you for the suggestion
