### ISSUE TITLE
Fancymenu Compatibility

### ISSUE THREAD

**Issue by Its-Just-Luci** [juancarloscp52/BedrockIfy#299]
Hi, I was wondering if you could adjust the layering used on the main menu and title screen to be compatible with [Fancymenu ](https://modrinth.com/mod/fancymenu?hl=en-US) as currently, the two appear to be mutually exclusive. Enabling customization presently hides everything on the screen, which isn't ideal as I'd really like to keep the loading tooltips and logo, and can't adjust the background. Photos added, first is without customization enabled
![2023-09-20_20 35 39](https://github.com/juancarloscp52/BedrockIfy/assets/57868183/90c6183d-3c96-43b7-bd99-48c0cea59073)
![2023-09-20_20 35 43](https://github.com/juancarloscp52/BedrockIfy/assets/57868183/9701803f-bc75-45ad-a6a2-850fa778a27c)

**Comment by Its-Just-Luci** [comment]
bumping this as I haven't heard anything in 2 weeks

**Comment by Its-Just-Luci** [comment]
https://github.com/Keksuccino/FancyMenu/issues/606 also made a new issue post on FancyMenu

**Comment by Its-Just-Luci** [comment]
bumping as it has been **_over a month_** and I have yet to hear from the bedrockify team

**Comment by seriousfreezing** [comment]
![image](https://github.com/juancarloscp52/BedrockIfy/assets/66693072/57dde759-56a1-403e-b056-b13d0f23d221)
There is a feature in FancyMenu that removes shadows from headers and footers, Bedrockify breaks this.
