### ISSUE TITLE
Tupade to 1.20.2 PLS

### ISSUE THREAD

**Issue by MerlinTheHobkin** [juancarloscp52/BedrockIfy#302]
i love your mod man can u pls update it to 1.20.2 ?

**Comment by juancarloscp52** [comment]
Hello! I'm coming from a long modding break, I have to sort out some pull request and issues first, but expect a release for a new Minecraft version in one to two weeks.

**Comment by MerlinTheHobkin** [comment]
thx man i love your mod so much i wich it is a part of the original game

**Comment by juancarloscp52** [comment]
Update released on modrinth and curseforge (waiting for moderation approval)

**Comment by MerlinTheHobkin** [comment]
nice thx


Am So., 8. Okt. 2023 um 14:01 Uhr schrieb Juan Carlos <
***@***.***>:
