### ISSUE TITLE
[1.20.6] Safe Screen Area not working as intended.

### ISSUE THREAD

**Issue by Soufre** [juancarloscp52/BedrockIfy#339]
The armor hud ignores the Safe Screen Area configuration, only Bedrockify and the latest [Fabric API jar](https://modrinth.com/mod/fabric-api/version/0.98.0+1.20.6) were present while testing.

![2024-05-07_22 17 25](https://github.com/juancarloscp52/BedrockIfy/assets/96512010/1b522c25-9a82-48c8-9c4f-8265431ca666)

**Comment by juancarloscp52** [comment]
Woops! Fixed now! thanks for opening the issue!
