### ISSUE TITLE
Idle hand animation speed broken since 1.20.5

### ISSUE THREAD

**Issue by MidyGamy** [juancarloscp52/BedrockIfy#342]
Hello, I just updated my Minecraft to 1.20.6 and I noticed the Idle hand animation got too fast, and it's due to the framerate, since if i lock my FPS at 60, the animation look like it should work, but when I set high FPS, the animation speed is faster (and this issue weren't in Bedrocklfy on 1.20.4)

https://github.com/juancarloscp52/BedrockIfy/assets/95078425/7c1f9382-529b-44e0-ac1b-2fdf2a9684f1

**Comment by juancarloscp52** [comment]
Thanks for reporting this issue! new version is now available in all platforms!
