### ISSUE TITLE
[COMPAT BUG] Mod breaks pinning recipes from Better Recipe Book [Fabric, 1.20.1]

### ISSUE THREAD

**Issue by SafTheLamb** [juancarloscp52/BedrockIfy#348]
When installed alongside Better Recipe Book https://modrinth.com/mod/brb, Fabric 1.20.1, the pin recipe feature from Better Recipe Book no longer works :(
Bedrockify Version: 1.9.1+mc1.20
Better Recipe Book Version: 1.10.0+1.20.0-1

**Comment by juancarloscp52** [comment]
seems to be working on 1.10.0-rc5 for mc 1.20.1
