### ISSUE TITLE
Sun Glare is way too different from Bedrock

### ISSUE THREAD

**Issue by kikawaa** [juancarloscp52/BedrockIfy#359]
Sun glare in Bedrock Edition makes sun becomes bigger brighter/adds intensity, sky changes its color tint a little bit, fog changes color too, and clouds become darker, a sun color tint changes depending on biome (not sure about this because that might be sky color which changes depending on biome that makes it look like sun changes its color instead) while in this mod sky becomes darker and sun just becomes bigger (and apparently also darker) it looks or impressive on Bedrock in my opinion, there is currently no mods or shaders that add accurate sun glare from Bedrock so it would be really nice if you added it, ideally it should look like it does on the video below, I also attached video showing how it currently looks in BedrockIfy so it will be easier to compare them

https://github.com/user-attachments/assets/a7321348-fc7c-4085-a211-55e4a794f4ca

https://github.com/user-attachments/assets/66924143-91cb-4f7c-8bb6-e45151fe029a

**Comment by juancarloscp52** [comment]
https://github.com/user-attachments/assets/9f32cb4d-c2a1-4c59-bf13-4b27139e6fda

Okey, so I've matched the darkned sky color to bedrock, increased sun sprite brightness when looking at it and darkened the clouds a bit. I'm not sure if the video will be able to show it due to compression, but its very close to bedrock. At the moment i don't plant on changing fog. Thanks for the suggestion!

**Comment by juancarloscp52** [comment]
At the moment i dont plant on changing fog.

**Comment by kikawaa** [comment]
Thank you so much for the update, it would be really nice though if you did change the fog, at least in the future, that would be awesome, and if you will change then please make sun a little bit brighter as well so it will be even more beautiful (without making fog darker sun will look too bright on sunrises and sunsets so don't change it before fog)
