### ISSUE TITLE
[Mod conflict] Crashes with Skin Swapper

### ISSUE THREAD

**Issue by K0-RR** [juancarloscp52/BedrockIfy#36]
Reported to Skin Swapper - https://github.com/cobrasrock/Skin-Swapper/issues/7
crash report - https://hatebin.com/gqobhslpas
latest.log - https://hatebin.com/pgzchhyavd

**Comment by juancarloscp52** [comment]
Hi! try the temporal fix purposed in #33. I'll try to upload a real fix for this issue later this month.

**Comment by juancarloscp52** [comment]
The cause of this crash has been fixed in the latest BedrockIfy version. You should be able to use Panorama Background with this mod without any crashes!
