### ISSUE TITLE
Resourcepack's hotbar selection box has a black line at the bottom

### ISSUE THREAD

**Issue by egirlcatnip** [juancarloscp52/BedrockIfy#361]
I'm currently using the resourcepack Catppuccin, for GUI. I'd like to edit/update it to get rid of the black line at the bottom of the hotbar selection texture. Using the screen safety area feature set to 3px.

![image](https://github.com/user-attachments/assets/e96d116d-3689-4a93-bab7-f838e1f8fc40)

The texture is a 22x21 image:
![hotbar_selection](https://github.com/user-attachments/assets/2e7a9818-b019-43bc-a333-bebe91df2a21)

Can someone please help me fix this? <3

This is how it's supposed to look like: (note that the black line would not be visible, because vanilla doesn't have screen safe area)
![Untitled](https://github.com/user-attachments/assets/ff4bd4c2-3aa5-4ca4-8776-07dee9e91194)

**Comment by egirlcatnip** [comment]
If an tranasparent 1x1 image is used as hotbar_selection.png, the line stays:
![image](https://github.com/user-attachments/assets/c2e0b5dc-453a-4c84-91c9-ef1397c6153a)

**Comment by egirlcatnip** [comment]
Aditionally, a fix could be to create an options toggle of disabling the slot highlight texture being enlarged.

**Comment by juancarloscp52** [comment]
Hello! I've added a new option on "screen safe area" settings that disables this line. You can find the option as "Show Hotbar Selector overhang:" and set it to false.

This will be included in a future bedrockify version, hopefully to release soon.
