### ISSUE TITLE
sun glare causes game to crash with sodium installed 1.21.1

### ISSUE THREAD

**Issue by AnukWarrior** [juancarloscp52/BedrockIfy#363]
running the latest versions of bedrockify with sodium on 1.21.1 (with and without indium) will cause the game to crash on boot unless you turn off the sun glare mixin in the config

logs

[latest.log](https://github.com/user-attachments/files/16571051/latest.log)

[crash-2024-08-11_10.28.37-client.txt](https://github.com/user-attachments/files/16571054/crash-2024-08-11_10.28.37-client.txt)

only mods loaded while testing these are
bedrockify-1.10+mc1.21
fabric-api-0.102.0+1.21.1
sodium-fabric-0.5.11+mc1.21

fabric loader is 0.16.0-1.21.1

**Comment by juancarloscp52** [comment]
Thank you for letting me know! Fixed in 23d0dbf6d9465d218e02a6054db9777e6a5f5c1e, to be released later today!
