### ISSUE TITLE
[Weird mod conflict] Requiem-pandemonium crashes game when these 3 mods are loaded alongside.

### ISSUE THREAD

**Issue by K0-RR** [juancarloscp52/BedrockIfy#37]
https://github.com/Ladysnake/Requiem/issues/198

Fabric Loader 0.10.8. Without Pandemonium game loads normally. If one of the mods with bold names isn't present then the game loads normally too.

Mods:
fabric-api-0.28.0+1.16
modmenu-1.14.13+build.19
requiem-1.3.0
requiem-pandemonium-1.3.0
[1.16.4]+Flight+Rings+1.4.2
accurate-block-placement-1.0.8
bedrockify-0.2.0-1.16.2+

crash report - https://hatebin.com/jwndniadfc
latest.log - https://hatebin.com/byynzcwzwu

**Comment by juancarloscp52** [comment]
Fixed on the Requiem side ;)
