### ISSUE TITLE
Hotbar differences

### ISSUE THREAD

**Issue by supsm** [juancarloscp52/BedrockIfy#38]
The bedrock hotbar is slightly floating above the bottom edge of the window, whereas the java hotbar is attached. Consider adding this?

**Comment by juancarloscp52** [comment]
Hi! You can change the distance from the border of the hotbar in bedrockify settings, visual improvements with the setting "screen safe area".

**Comment by supsm** [comment]
I don't really want to mess anything else up though. In bedrock the hotbar is floating, but coordinates for example are still at the edge.
