### ISSUE TITLE
Paper Doll doesn't have full brightness

### ISSUE THREAD

**Issue by Snivine** [juancarloscp52/BedrockIfy#39]
In the normal bedrock edition the paper doll has no shadowing, which means it always has full brightness, this is not the case in BedrockIfy since the paper doll does have shadows and lightning

This is a parity issue so should be low piority but it looks odd

How it looks: (ignore the glitches)
![2020-12-23_19 32 43](https://user-images.githubusercontent.com/72054019/103117944-644cdc80-4632-11eb-9b19-a1d8d2741761.png)

How it should look: I'll add it in another comment

**Comment by Snivine** [comment]
![Screenshot_20201225_225550_com mojang minecraftpe](https://user-images.githubusercontent.com/72054019/103145716-60898a80-4704-11eb-9646-877de841453d.jpg)
Sorry for being late but I forgot I posted this and was actually about to post it again
anywho this is how it's supposed to look

**Comment by juancarloscp52** [comment]
Hi! I've already try to implement the same lighting without any success. For now, I will close this issue but I'll continue to explore other solutions.
