### ISSUE TITLE
Idle Hand Animation

### ISSUE THREAD

**Issue by FavoritoHJS** [juancarloscp52/BedrockIfy#4]
When you hold an item in your hand, it moves slightly, even if you aren't doing anything. Consider adding this to the mod.
[Demonstration](https://github.com/juancarloscp52/BedrockIfy/files/5133972/idle.zip) [Video inside .zip]

**Comment by juancarloscp52** [comment]
Good Idea, I'll add it to my TODO list.

**Comment by juancarloscp52** [comment]
This feature is now included in BedrockIfy! (22395f0b94b6de9d539e086f60a31e37526a6829)
You can test it in the [latest release](https://github.com/juancarloscp52/BedrockIfy/releases/tag/0.1.3-1.16.2%2B)
