### ISSUE TITLE
(1.16.4) Coordinates Display doesn't respect reduced debug info

### ISSUE THREAD

**Issue by DarianLStephens** [juancarloscp52/BedrockIfy#41]
If a client installs this mod and connects to a server with the reduced debug info gamerule, it will allow you to see your coordinates with your display.
I propose that the coordinate display be automatically disabled if that gamerule is active.

**Comment by juancarloscp52** [comment]
Totally forgot that game rule existed...
Thanks for the suggestion, I'll try to have it implemented in the next update.

**Comment by juancarloscp52** [comment]
Implemented with commit 4438adf8e1a453a95e460cb110c412f5845071c1. You can build bedrockIfy from the stable branch source or wait until the next version is released!
