### ISSUE TITLE
Video settings background spins very fast when frames are uncapped

### ISSUE THREAD

**Issue by supsm** [juancarloscp52/BedrockIfy#42]
The title says it all. If I turn off vsync and uncap my frames, the background start spinning very quickly. As soon as I turn them back on, it goes back to normal speed.

**Comment by supsm** [comment]
Also, when I cap my frames, the background spins slowly.

**Comment by juancarloscp52** [comment]
A fix was released with the latest bedrockIfy version (0.2.2) and should now work properly. Thanks for opening this issue!
