### ISSUE TITLE
Quick armor swap doesn't work

### ISSUE THREAD

**Issue by supsm** [juancarloscp52/BedrockIfy#43]
Quick armor swap doesn't actually work. It appears to work in the inventory, but the armor bars aren't actually changed, and opening a chest can cause your inventory to update. It gets quite confusing when that happens. It seems to me that the mod doesn't send any packets to the server when it swaps. (could be totally wrong, just a guess)

**Comment by juancarloscp52** [comment]
The current implementation of quick armor swap doesn't work on servers. I'm looking forward to writing a better implementation when I have some free time. For now, you should disable quick armor swap if connected to a server.

**Comment by juancarloscp52** [comment]
Hi! The a new implementation of QuickArmorSwap that works on multiplayer has been released with BedrockIfy 0.2.2. You can download this version from the [releases](https://github.com/juancarloscp52/BedrockIfy/releases) page! Thanks for opening this issue!

**Comment by supsm** [comment]
Thanks so much! This was one of the features a was most looking forward to :)
