### ISSUE TITLE
Realms screen crash

### ISSUE THREAD

**Issue by Snivine** [juancarloscp52/BedrockIfy#44]
Realm screen crashes when using bedrockify, I'm not certain that is bedrockify but I think it might be because of this line in the crashlog: "at net.minecraft.class_350.redirect$zli000$**renderPanorama**(class_350.java:621)" a thing that vanilla shouldn't do in the realms screen and only bedrockify does

https://paste.ee/p/3fGRK

**Comment by juancarloscp52** [comment]
Hi! This crash was fixed with the last version. Please update BedrockIfy to version 0.2.1.
