### ISSUE TITLE
"Quick Armor Swap" causes crash when right-clicking non-armor item

### ISSUE THREAD

**Issue by Leo40Git** [juancarloscp52/BedrockIfy#47]
I just wanted to eat some steak...

**Crash log:** https://pastebin.com/GDmZGwws

**Comment by juancarloscp52** [comment]
Thanks for opening the issue! I'll try to have it fixed for today/tomorrow. For now can disable quick armor settings on the bedrockIfy menu under "other settings" category. Or you can go back to the previous release.
