### ISSUE TITLE
Chat Tooltip desync

### ISSUE THREAD

**Issue by Afrocntrik** [juancarloscp52/BedrockIfy#5]

**Comment by juancarloscp52** [comment]
Does the paper doll show up while sprinting/sneaking or elytra flying?

**Comment by Afrocntrik** [comment]
Yes my bad, however with the chat there is desync between the advancement tooltip and text

**Comment by Afrocntrik** [comment]
![2020-09-01_18 12 04](https://user-images.githubusercontent.com/11052983/91911341-df9f1280-ec7e-11ea-9aa0-da0b11bab864.png)
My mouse is where the tooltip appears but there's no advanement there nor can i click coordinates

**Comment by juancarloscp52** [comment]
Ok, I confirm that this is a bug, I'll try to fix it for the next release. Thanks!

**Comment by juancarloscp52** [comment]
Bug Fixed! **Thanks for reporting this bug**. You can test fix by building BedrockIfy from source, or you can wait until the next release!.
