### ISSUE TITLE
Error in the console.

### ISSUE THREAD

**Issue by K0-RR** [juancarloscp52/BedrockIfy#53]
[main/WARN]: WARNING! Mod bedrockify is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.

**Comment by juancarloscp52** [comment]
This warning is due to the latest update on Mod Menu. As BedrockIfy is compatible with versions versions prior to 1.16.5 it needs to use this deprecated method to maintain compatibility. This issue will be resolved with minecraft release 1.17.
