### ISSUE TITLE
Enchanted item tooltip undercounts number of enchantments

### ISSUE THREAD

**Issue by JustSparkyYes** [juancarloscp52/BedrockIfy#54]
If an item has more than 4 enchantments, the "and X more..." string undercounts the number of enchantments by 1.

![2021-02-02_10 07 44](https://user-images.githubusercontent.com/78430582/106622736-e689c400-6541-11eb-94c6-fa1f913c5f6a.png)
![2021-02-02_10 07 50](https://user-images.githubusercontent.com/78430582/106622764-ee496880-6541-11eb-86fd-2cbc6fa23f3d.png)

**Comment by juancarloscp52** [comment]
Thanks for reporting this issue! The fix will be available in the next release of BedrockIfy!
