### ISSUE TITLE
New quick armor swap issue

### ISSUE THREAD

**Issue by JayCeeCreates** [juancarloscp52/BedrockIfy#56]
While the game crash regarding quick armor swap has been fixed, it now presented another issue.

My gameplay prefers LMB to interact and RMB to attack/destroy. Now it seems like most item-related events like eating food and preparing bow and arrow don't work.

**Replicating the problem:**
- Assign LMB to interact and RMB to attack/destroy on controls
- Perform an item-related event in-game

It works with the default mouse controls, though.

**Comment by juancarloscp52** [comment]
Hi! Thanks for reporting this issue. It has been fixed and will be released with the next version of bedrockify in some days. Until then,  you can try this [snapshot](https://github.com/juancarloscp52/BedrockIfy/files/5938967/bedrockify-0.2.4-SNAPSHOT.zip)!
