### ISSUE TITLE
Seamless Incompatiabilty

### ISSUE THREAD

**Issue by timelady-victorious** [juancarloscp52/BedrockIfy#57]
There is a crash caused by the [Seamless Loading Screen mod](https://www.curseforge.com/minecraft/mc-mods/seamless-loading-screen) caused by the Fabric Rendering API. This doesn't bother me, per sey, as I use Not Enough Crashes, and I was going to the main screen anyways. But its still an issue.

Crash Log: https://paste.ee/p/Rc7dc
Minecraft Log: https://paste.ee/p/i1WlM

**Comment by juancarloscp52** [comment]
Hi! Given the provided crashlogs, I cannot confirm this issue is caused by BedrockIfy at all as it does not interfere with that part of the API. It might be caused by other mods.
