### ISSUE TITLE
Shulker Box Tooltip Compatiability

### ISSUE THREAD

**Issue by timelady-victorious** [juancarloscp52/BedrockIfy#61]
When holding a shulker box with bedrockify and shulker box tootip, the shulker box states its contents like in vanilla, instead of showing its contents like it should. It still works in GUIs
![image](https://user-images.githubusercontent.com/73656286/108226892-34ebb500-7135-11eb-8a97-265719267d9b.png)

![image](https://user-images.githubusercontent.com/73656286/108227218-94e25b80-7135-11eb-9716-fc7c39406f50.png)

**Comment by juancarloscp52** [comment]
Hi! The tooltips are shown as intended with bedrockIfy (showing a short list of elements in the held item tooltips and in inventories tooltips). In case that Shulker box tooltips includes its own held item tooltips, you can disable the "client.features.heldItemTooltips" mixin in the mixin category of bedrockIfy settings.
![2021-02-18_12 12 27](https://user-images.githubusercontent.com/11300094/108348893-a0d82700-71e2-11eb-8769-2584df3e7f98.png)
![2021-02-18_12 12 40](https://user-images.githubusercontent.com/11300094/108348902-a33a8100-71e2-11eb-9565-e0c3ca03d844.png)

**Comment by timelady-victorious** [comment]
Yes, I know that. But it would be nice if you made the tooltip show like with Shulker Box Tooltip if Shulker Box Tooltip is installed

**Comment by juancarloscp52** [comment]
This change is a bit out of the scope of bedrockIfy and might be better suited to be a standalone mod or a feature of Shulker Box Tooltip
