### ISSUE TITLE
Feature request: Bedrock-like creative mode

### ISSUE THREAD

**Issue by supsm** [juancarloscp52/BedrockIfy#62]
In bedrock edition, flight is changed so there is no momentum (i.e. java edition flight is like walking on ice, bedrock is on normal blocks). In java edition, this momentum can be annoying when building things in creative. Bedrock also places blocks faster in creative mode, and breaks them faster as well.

**Comment by Saraistupid** [comment]
i think the placing part should be changeable, it'll be a huge anticheat concern

**Comment by juancarloscp52** [comment]
I've been looking into disabling the momentum in creative, but I've been unable so far. I'll close this issue for now

**Comment by supsm** [comment]
Whoops, I forgot about this. In case anyone wants momentum to be disabled, LambdaControls has an option for that.

**Comment by Tanza3D** [comment]
any chance to get a bedrock-like placing mechanism, where it keeps your blocks in line when you fly and hold click? very helpful for building, called "fast place" i think. seems like it adds into this
