### ISSUE TITLE
Server crash with Bedrockify: Exception in server tick loop  java.lang.NoClassDefFoundError: net/minecraft/class_310

### ISSUE THREAD

**Issue by Ensrick** [juancarloscp52/BedrockIfy#63]
The server crashes after about 5 minutes or so with this crash log

[crash-2021-03-13_15.20.55-server.txt](https://github.com/juancarloscp52/BedrockIfy/files/6136264/crash-2021-03-13_15.20.55-server.txt)

**Comment by juancarloscp52** [comment]
Hi! Thanks for reporting this issue! Please try the following version and tell me if it solved the crash on your server:
[bedrockify-0.2.6-SNAPSHOT.zip](https://github.com/juancarloscp52/BedrockIfy/files/6136471/bedrockify-0.2.6-SNAPSHOT.zip)
