### ISSUE TITLE
Text almost unreadable in Iris (Starline)

### ISSUE THREAD

**Issue by squishycat92** [juancarloscp52/BedrockIfy#65]
Hi, 
This is an amazing mod (particularly the loading screens!), but I've noticed that the starline branch of Iris's configuration screen conflicts with the panorama, making the text very hard to read (relates to issue #23). Perhaps it would be possible to disable the panorama on the configuration screen?

With panorama:
![image](https://user-images.githubusercontent.com/62223616/112061733-26216500-8b1c-11eb-9b50-e133503a9586.png)

Without panorama:
![image](https://user-images.githubusercontent.com/62223616/112061824-4b15d800-8b1c-11eb-900a-6dabbcee4bb2.png)

Thanks!

**Comment by juancarloscp52** [comment]
Thanks for reporting this issue! You can try the fix by building from source or wait some days until it is officially released!
