### ISSUE TITLE
[Enhancement] Allow modifying loading tips with an external JSON file.

### ISSUE THREAD

**Issue by Tux-Prowess** [juancarloscp52/BedrockIfy#69]
I have created a custom modpack for personal use as of now, but if I do decide to release it to the public, I want to take advantage of the loading tips to provide important information about how to work with the mods, such as how to tame and work with companion bats and subtle oddities with some of the mods to watch out for. I think it would make for another way to teach the player without them having to read a couple hundred paragraph readme file or a separate wiki.

**Comment by juancarloscp52** [comment]
Good Idea! I'll look into implementing this as soon as I can!

**Comment by juancarloscp52** [comment]
Added with 463c6bc699db66caf2308e60b0c862dd4628bf5a.

Now, when launching bedrockIfy it will create a .json file in ./minecraft/config named bedrockify-ExternalLoadingTips.

The file contains two fields: 
A boolean, that if true, the external tips will be the only ones shown.
`"alwaysExternalTips":false`
And a string array that will contain all the new tips.
`"externalLoadingTips":["tip 1", "tip2"]`
