### ISSUE TITLE
The panoramic menu does not move urgently!

### ISSUE THREAD

**Issue by ghost** [juancarloscp52/BedrockIfy#73]
fter installing the mod, starting from version 0.2.3 the panoramic menu stopped moving
You tobish the background

**Comment by K0-RR** [comment]
Duplicate of https://github.com/juancarloscp52/BedrockIfy/issues/50

**Comment by juancarloscp52** [comment]
@MiFliK please check and try: https://github.com/juancarloscp52/BedrockIfy/issues/50#issuecomment-833827217
