### ISSUE TITLE
Separate server-side settings

### ISSUE THREAD

**Issue by Madis0** [juancarloscp52/BedrockIfy#76]
It would be nice if you could separate the server-side and packet-changing settings (fallen trees, reach-around blocks, shift to show shield etc.) from the rest, maybe as a separate tab. 

Separating them would give users a better overview on what to disable when playing in multiplayer servers to prevent getting banned and make it easier for one to play vanilla Java worldgen without any modifications.

**Comment by juancarloscp52** [comment]
Thats a good idea! I'll try to get it done for the next release!

**Comment by SulpherStaer** [comment]
Added to this I'd like to know if Bedrockify is required server side to prevent such wrong kicking / blocking from illegal actions, or packet desync.

**Comment by juancarloscp52** [comment]
It is not required to be server side, although some features won't work. Reach around block placement will work as it is implemented clientside, but might be considered cheating, so talk with server administration before using it.

**Comment by SulpherStaer** [comment]
I am server administration :P hence me asking

**Comment by juancarloscp52** [comment]
in that case, there should be no problem with invalid packages when bedrockIfy isn't serverside as all serverside features are loaded during world creation
edit: Also, the only serverside features are fallen and dead trees (world generation) and bedrock crafting recipes (the recipes are always managed serverside)

**Comment by juancarloscp52** [comment]
Finally I've decided to separate settings by logical sides only on config files, but for now, The settings in the bedrockIfy menu will still have the options organized in the same way as always.
