### ISSUE TITLE
Bugs in new update

### ISSUE THREAD

**Issue by Dacha54** [juancarloscp52/BedrockIfy#77]
With this **new** update,
my minecraft panorama move, but slowly with bugs, i only have api and bedrockify.
I have black line on grass block in the distance.
And i also have java and bedrock loading screen. I have your with tips and line, i also have java cube loading at the bottom of the screen.
This things works in previous updates.
**I also try your steps when panorama don't move but that doesn't work.**
(Also, srry for my english)

**Comment by juancarloscp52** [comment]
Hi! Can you please share some screenshots with these bugs if posible? So I can better understand what is happening.

Also, please insert the minecraft log of a game session and pc specifications.

**Comment by Dacha54** [comment]
![IMG_20210510_121231](https://user-images.githubusercontent.com/83943909/117643742-048e4280-b189-11eb-8144-60d7e57d9b3b.jpg)
![IMG_20210510_121332](https://user-images.githubusercontent.com/83943909/117643855-27205b80-b189-11eb-84be-843fb1c99f86.jpg)
I cant take picture where panorama doesnt move. And i think you see dark line, i need to screenshot with Phone. 
Pc:
AMD Ryzen 3 2300X quad core processor
Invidia geforce gtx 1050

**Comment by juancarloscp52** [comment]
Does the black line persist when bedrockIfy is disabled?

**Comment by Dacha54** [comment]
No only when i use this mod also in snapshot but thats no metter

**Comment by Dacha54** [comment]
Somehow I solve the problem with the panorama and now everything works, but is this need to be like this or not? 
![IMG_20210513_102445](https://user-images.githubusercontent.com/83943909/118099459-8ecae680-b3d5-11eb-8bb1-b53c618731d8.jpg)
 Java and bedrock loading together.

**Comment by juancarloscp52** [comment]
Yes, try disabling the option "Loading Screen Chunk Map:" on bedrockIfy Settings

**Comment by Dacha54** [comment]
Thank,
No everything works fine. 
Best mod.
Thanks again. 
Every problem solved.

**Comment by Jaozim-123** [comment]
I'm having some issues with the coordinates, they're not showing, neither does the fps when I let it on [with coordinates]
![image](https://user-images.githubusercontent.com/84182391/118262001-a7e19f00-b48a-11eb-8296-a503029558b4.png)
![image](https://user-images.githubusercontent.com/84182391/118262072-c2b41380-b48a-11eb-8904-85d9657c844b.png)
For those who're having the same issue, just disable, reduced debug info on chat settings

**Comment by juancarloscp52** [comment]
> For those who're having the same issue, just disable, reduced debug info on chat settings

Thats actually a feature. If the world has enabled the reduced debug info gamerule, it will not show coordinates on screen,
