### ISSUE TITLE
Floating hotbar

### ISSUE THREAD

**Issue by Dakedres** [juancarloscp52/BedrockIfy#89]
I would love if there was an option to allow the [margin between the hotbar and the edge of the screen](https://feedback.minecraft.net/hc/user_images/PGX9KDt5H2MPop1csyLbmA.png) seen in Bedrock and older console editions.

I gew up on those old editions, and when playing Forge packs I always install the Console Experience mod solely for this feature. Iwish I could have it on my fabric vanilla client, and I believe it would be a worthy addition to this mod. Thanks

**Comment by juancarloscp52** [comment]
Hi! This feature already exists in BedrockIfy. You can configure it in the BedrockIfy Settings Menu, with an option called "Screen Safe Area". With that option you can set the height that you want.

**Comment by Dakedres** [comment]
Oh I see, I probably couldn't find it because I was looking for a different name. Thanks
