### ISSUE TITLE
Entity Rendering in Fast grahpics

### ISSUE THREAD

**Issue by E404NNF** [juancarloscp52/BedrockIfy#9]
I saw that the rendering of entities isn't really replicated that well when it comes to fast graphics (i still didn't test fancy graphics yet)
The equivalent of Fast graphics on java is the Fancy graphics on bedrock when it comes to entities rendering
Here are pictures (Entities are lighter on Bedrock fast graphics, yes, even block entities):
![Screenshot from 2020-09-26 20-07-31](https://user-images.githubusercontent.com/37207067/94347511-2ccf9380-0035-11eb-995c-b271b57b50f0.png)
![2020-09-26_18 48 12](https://user-images.githubusercontent.com/37207067/94347528-47a20800-0035-11eb-9f65-517803597595.png)

**Comment by juancarloscp52** [comment]
Hi! 
Yeah, that feature isn't implemented on bedrockIfy. I actually didn't know that was the behavior on bedrock edition. I guess I can take a look in a near future to implement something similar.

**Comment by E404NNF** [comment]
Aight!

**Comment by E404NNF** [comment]
Here's a screenshot using Fancy Graphics
![bugrockedition69](https://user-images.githubusercontent.com/37207067/94369214-b0968800-00e8-11eb-89b0-0b77411f420f.png)

**Comment by Saraistupid** [comment]
any updates in the progress? (if there's any)

**Comment by juancarloscp52** [comment]
I've tried many things with the current implementation of entity rendering but I've been unsuccessful to achieve these results. I currently lack the necessary knowledge. I'll still be trying as this feature might be useful for other implementations, but cant promise anything.
(This also applies to issue #12)

**Comment by Saraistupid** [comment]
Aight thanks, I'm waiting for it! Hope you'll get the knowledge soon

**Comment by Saraistupid** [comment]
Will you close this one too?

**Comment by juancarloscp52** [comment]
for now yes
