### ISSUE TITLE
When we eat with the left hand, the overlay of said hand is not seen

### ISSUE THREAD

**Issue by TheSrBig** [juancarloscp52/BedrockIfy#93]
if I put a meal in the left hand (second hand) the overlay (if we have it) disappears when doing the eating animation

**Comment by TheSrBig** [comment]
Also, the bedrock crafting does not work in the mod

**Comment by juancarloscp52** [comment]
Hi! I'm not able to reproduce any of this issues with the latest version of bedrockIfy. By overlay, you mean the position text and the paperdoll? 

And the bedrock crafting recipies are working for me. What recipes do not work for you?

Finally, if you can tell me if you are using other mods and what minecraft version are you using.

**Comment by TheSrBig** [comment]
i use a mod called xaeros minimap, optifine with optifabric and an advanced xray and a mod called apple skin just those

**Comment by juancarloscp52** [comment]
could you try bedrockIfy without these mods and tell me if the issue is still happening? And also just without optifine/optifabric just to check

**Comment by TheSrBig** [comment]
I already removed the mods, and the bedrock crafting still does not appear

**Comment by juancarloscp52** [comment]
hmmm, what version of bedrocIfy and Minecraft are you using? What recipe is not working for you?

Also, make sure you have enabled the option "Use Bedrock Crafting Recipes" and the "common.features.recipes" mixin inside the bedrockIfy settings menu.

**Comment by juancarloscp52** [comment]
Also, note that bedrock Crafting recipes only works on single player, or on server where bedrockIfy is installed serverside

**Comment by juancarloscp52** [comment]
Closed due to inactivity
