### ISSUE TITLE
Option to disable "Bedrockify Settings" button from Options.

### ISSUE THREAD

**Issue by K0-RR** [juancarloscp52/BedrockIfy#94]
- it's still accessible via the cloth config button in Mod Menu
- can interfere with other buttons added by other mods
- kinda doesn't below there in my opinion as this is for game settings but I understand this is a big mod and not everyone knows how to access its settings in other ways

**Comment by juancarloscp52** [comment]
Hi! This feature is already in bedrockIfy. You can disable the bedrockIfy Settings buttons in the settings screen, "Other Settings" and disabling "Show BedrockIfy Settings Button"

**Comment by K0-RR** [comment]
Sorry! Not sure how I missed it the first time.
