### ISSUE TITLE
When chat window is moved down because F3 menu got opened the links hitbox isn't being moved down.

### ISSUE THREAD

**Issue by K0-RR** [juancarloscp52/BedrockIfy#95]
![Screenshot from 2021-08-31 12-37-39](https://user-images.githubusercontent.com/43277609/131488267-3427ef1c-b091-4ed7-99f9-8de1610b7bee.png)

You can't click the green text to tp

because the hitbox is still up there (you can't see it but when you click you get tp):

![Screenshot from 2021-08-31 12-38-30](https://user-images.githubusercontent.com/43277609/131488546-a8f7dc71-d0fe-44d2-ab3f-89d114881b98.png)

**Comment by juancarloscp52** [comment]
Thanks for opening this issue! should be fixed right now. The patch will be published with the next update
