### ISSUE TITLE
Minor issues with XP & Chat/Position text

### ISSUE THREAD

**Issue by shaddatic** [juancarloscp52/BedrockIfy#96]
These four issues are very small, but they're just a few things I've noticed; but they hardly bring down this awesome mod!

1. The XP level text is the wrong color; the difference is minor, but Bedrock uses the color 0x7FFF00 while Java uses 0x7EFC20, and the current code passes on the Java color to the Bedrock text, meaning its technically incorrect. 
I fixed this by replacing the variable 'color' with 0x7fff00 in InGameHUDMixin.java

2. The Chat, Position text, (and by extension the paper doll) are locked to the top left of the screen on PC Bedrock. On console it does have a safezone, but on PC the safezone is entirely ignored. An option for this would be best, but temporarily I just added an 'if (screenBorder > 8)', and if it isn't, I just removed the screenBorder variable from the fill & textRenderer, which worked well enough for just me!

3. The border behind the Chat is perfect, but the Position border is actually 2 px taller with the P in "Position" (not including shadow) being 2 px from the bottom, and 3 px from the top. I got it to look perfect by doing:
fill(... posY + 12 ...) & client.textRenderer.drawWithShadow(... posY + 3 ...)

4. Items render above the Hotbar highlight square, but on Bedrock they render behind. I don't think anything can be done about this one, but I thought I'd at least note it. And speaking of things that probably aren't fixable: with useAnimations, only 2D sprites expand on Bedrock while 3D blocks/items stretch up just like Java.

As always, amazing work so far! The world noise feature alone makes this mod worth it, and I don't see myself living without it! Hope one day I can help out a little more!

**Comment by juancarloscp52** [comment]
Thanks for the input! I've never thought about these things. I'll take a look at it an update this issue asap!

**Comment by shaddatic** [comment]
Thank you for all your work! Even just the smaller features really just improve the Minecraft experience tenfold, thank you!
